config/routes.rb
Rails.application.routes.draw do


root 'doctors#index'

resources :doctors
resources :patients
resources :appointments, only: [:new, :create]
delete "/doctor/:doctor_id/appointment/:id", to: "appointments#destroy", as: "appointment"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :doctor
  belongs_to :patient
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    #validations
    validates_presence_of :name, :specialty

    #associations
    has_many :appointments, dependent: :destroy
    has_many :patients, through: :appointments
end

app/models/patient.rb
class Patient < ApplicationRecord
    #validations
    validates_presence_of :name, :age, :gender

    #associations
    has_many :appointments, dependent: :destroy
    has_many :doctors, through: :appointments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  def index
    @appointments = Appointment.all
  end
  
  def new
    #we are setting @doctors and @patients to map out as an 
    #array so that we can select from the list of doctors and
    #patients in our new appointment form

    @doctors = Doctor.all.map { |d| [d.name, d.id] }
    @patients = Patient.all.map { |p| [p.name, p.id] }
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(appointment_params)
      if @appointment.save
        redirect_to doctors_path
      else
        render :new
      end
  end

  def destroy
    doctor = Doctor.find(params[:doctor_id])
    appointment = Appointment.find(params[:id])
    appointment.destroy
    redirect_to doctor_path(doctor)
  end

private
  def appointment_params
    params.require(:appointment).permit(:doctor_id, :patient_id, :date)
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
 before_action :set_doctor, only: [:show, :edit, :update, :destroy] 
  
  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)
      if @doctor.save
        redirect_to @doctor
      else
        render :new
      end
  end

  def edit
  end

  def update
   
    if @doctor.update(doctor_params)
      redirect_to @doctor
    else
      render :edit
    end
  end

  def destroy
    @doctor.destroy
    redirect_to doctors_path
  end

private

  def set_doctor
    @doctor = Doctor.find(params[:id])
  end

  def doctor_params
    params.require(:doctor).permit(:name, :specialty)
  end

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  def index
    @patients = Patient.all
  end

  def new
    @patient = Patient.new
  end

  def show
    redirect_to patients_path
  end

  def create
    @patient = Patient.new(patient_params)
      if @patient.save
        redirect_to @patient
      else
        render :new
      end
  end

  def edit
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient
    else
      render :edit
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end
private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:name, :age, :gender)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointments/index.html.erb
<h1>All Appointments</h1>

<div>
    <ul>
    <% binding.pry %>
        <% for @appointments do |a| %>
        <li><%= a.

app/views/appointments/new.html.erb
<h1>Add an Appointment</h1>
<hr />

<%= form_for @appointment do |f| %>
    <%= f.select :doctor_id, options_for_select(@doctors) %>
    <%= f.select :patient_id, options_for_select(@patients) %>
    <%= f.text_field :date, required: true, placeholder: 'Date' %>

    <%= f.submit nil, class: 'btn' %>
<% end %>

<hr />
<%= link_to 'All Doctors', doctors_path %>
<%= link_to 'All Patients', patients_path %>

app/views/doctors/_form.html.erb
<%= form_for(doctor) do |f| %>
    <% if doctor.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(doctor.errors.count, "error") %> prohibited this doctor from being saved </h2>

        <ul>
        <% doctor.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
        </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name%>
    </div>

    <div class="field">
        <%= f.label :specialty %>
        <%= f.text_field :specialty %>
    </div>

    <div class="actions">
        <%= f.submit %>
    </div>
<% end %>

app/views/doctors/edit.html.erb
<h1>Edit Doctor</h1>

<%= render 'form', doctor: @doctor %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Specialty</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @doctors.each do |doctor| %>
            <tr>
                <td><%= doctor.name %></td>
                <td><%= doctor.specialty %></td>
                <td><%= link_to 'Show', doctor %></td>
                <td><%= link_to 'Edit', edit_doctor_path(doctor) %></td>
                <td><%= link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br />

<%= link_to 'New Doctor', new_doctor_path %>
<%= link_to 'Add Appointment', new_appointment_path %>

app/views/doctors/new.html.erb
<h1>New Doctor</h2>

<%= render 'form', doctor: @doctor %>

app/views/doctors/show.html.erb
<h1>Doctor: <%= @doctor.name %>

<% unless @doctor.specialty.empty? %>
    <p>
        <strong>Specialty:</strong>
        <%= @doctor.specialty %>
    </p>
    <hr />
<% end %>

<% if @doctor.patients.any? %>
<h5>Patients</h5>
<ul>
    <% @doctor.appointments.each do |appointment| %>
        <li>
            <%= appointment.patient.name %> - <%= appointment.date %> -
            <%= link_to 'Remove', appointment_path(@doctor, appointment), method: :delete, data: {confirm: "Really remove this appointment?" } %>
        </li>
    <% end %>
</ul>
<% else %>
    <h5>No Patients Found</h5>
<% end %>

<%= link_to 'All Doctors', doctors_path %>
<%= link_to 'Edit', edit_doctor_path(@doctor) %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OfficeVisit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
      <nav>
      <div class="nav-wrapper">
        <a href="/" class="brand-logo">Doctor Appointments</a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li> <%= link_to 'Doctors', doctors_path %> </li>
          <li> <%= link_to 'Patients', patients_path %> </li>
          <li> <%= link_to 'Add Appointment',new_appointment_path %> </li>
        </ul>
      </div>
    </nav>

    <% flash.each do |key, value| %>
      <div class="flash <%= key %>">
        <%= value %>
      </div>
    <% end %>

    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(patient) do |f| %>
    <% if patient.errors.any? %>
        <div id="error_explanation">
            <h2><% pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

            <ul>
            <%= patient.errors.full_message.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>

    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="field">
        <%= f.label :age %>
        <%= f.text_field :age %>
    </div>

    <div class="field">
        <%= f.label :gender %>
        <%= f.text_field :gender %>
    </div>

    <div class="actions">
    <%= f.submit %>
    </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Edit Patient Info</h1>

<%= render 'form', patient: @patient %>

app/views/patients/index.html.erb
<h1>Patients</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Age</th>
            <th>Gender</th>
        </tr>
    </thead>
    
    <tbody>
        <% @patients.each do |patient| %>
        <tr>
            <td><%= patient.name %> </td>
            <td><%= patient.age %> </td>
            <td><%= patient.gender %> </td>
            <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
            <td><%= link_to 'Delete Patient', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    </tbody>
</table>
<br />

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>